name: Deploy to Yandex Cloud

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # 1. Логин в Docker (ИСПОЛЬЗУЕМ НОВЫЙ ЭКШЕН)
    - name: Yandex Cloud CR Login
      uses: yc-actions/yc-cr-login@v2
      with:
        yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

    # 2. Сборка и отправка образа
    - name: Build and Push Docker Image
      env:
        CR_REGISTRY: crplem6q81s99h12l3s5
        CR_REPOSITORY: snake-game
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG .
        docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG

    # 3. Установка kubectl
    - name: Install kubectl
      uses: azure/setup-kubectl@v3

    # 4. Подключение к кластеру (ИСПОЛЬЗУЕМ НОВЫЙ ЭКШЕН)
    - name: Get K8s credentials
      uses: yc-actions/yc-k8s-cluster-get-credentials@v1
      with:
        yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
        cluster-id: catg7jnf6f1gdsu6moo4  # Твой новый кластер

    # 5. Деплой
    - name: Deploy to K8s
      env:
        CR_REGISTRY: crplem6q81s99h12l3s5
        CR_REPOSITORY: snake-game
        IMAGE_TAG: ${{ github.sha }}
      run: |
        sed -i "s|IMAGE_PLACEHOLDER|cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG|g" k8s/deployment.yaml
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
