name: Deploy to Yandex Cloud

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # 1. Устанавливаем официальную утилиту YC CLI (чтобы работали команды yc)
    - name: Install YC CLI
      uses: yc-actions/setup-yc@v1
      with:
        yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

    # 2. Логин в Docker реестр (через утилиту yc)
    - name: Login to Yandex Container Registry
      run: |
        yc container registry configure-docker

    # 3. Сборка и отправка образа
    - name: Build and Push Docker Image
      env:
        CR_REGISTRY: crplem6q81s99h12l3s5
        CR_REPOSITORY: snake-game
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG .
        docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG

    # 4. Установка kubectl
    - name: Install kubectl
      uses: azure/setup-kubectl@v3

    # 5. Получение доступов к кластеру (ЧЕРЕЗ КОМАНДУ, А НЕ ЭКШЕН)
    - name: Configure K8s Context
      run: |
        yc managed-kubernetes cluster get-credentials --id catg7jnf6f1gdsu6moo4 --external --force

    # 6. Деплой
    - name: Deploy to K8s
      env:
        CR_REGISTRY: crplem6q81s99h12l3s5
        CR_REPOSITORY: snake-game
        IMAGE_TAG: ${{ github.sha }}
      run: |
        sed -i "s|IMAGE_PLACEHOLDER|cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG|g" k8s/deployment.yaml
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
